### ISSUE TITLE
measurementTypeID or measurementValueID

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-for-biologging#17]
@sarahcd I noticed in the Mahoney use case that most deployment measurement have a `measurementValueID`. I would argue that these are `measurementTypeID`s (like you have used for `gps:fix-type` and alike. The URLs don't differ for different values and don't describe a specific value like `collar` (although it is mentioned):

measurementType |  measurementValue | measurementValueID
--- | --- | ---
attachment-type | collar | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000052/
attachment-type | collar | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000052/
attachment-type | collar | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000052/
deployment-end-type | removal | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000084/
deployment-end-type | removal | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000084/
deployment-end-type | removal | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000084/
deployment-id | 166560_Summer | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000085/
deployment-id | 166760_Winter | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000085/
deployment-id | F53 | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000085/
duty-cycle | 5-min fixes | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000086/
duty-cycle | 5-min fixes | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000086/
duty-cycle | GPS: 4-h fixes; activity: 5-min averages | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000086/
manipulation-type | none | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000155/
manipulation-type | none | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000155/
manipulation-type | none | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000155/
study-site | Idaho National Engineering Laboratory | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000175/
study-site | Idaho National Engineering Laboratory | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000175/
study-site | Monroe Mountain, Fishlake National Forest | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000175/
tag-manufacturer-name | Lotek | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000183/
tag-manufacturer-name | Lotek | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000183/
tag-manufacturer-name | Lotek | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000183/
tag-model | GPS3300S | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000185/
tag-readout-method | tag-retrieval | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000188/
tag-readout-method | tag-retrieval | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000188/
tag-readout-method | tag-retrieval | http://vocab.nerc.ac.uk/collection/MVB/current/MVB000188/

**Comment by sarahcd** [comment]
@peterdesmet your suggestion makes sense to me, I moved everything to measurementTypeID.
