### ISSUE TITLE
Use T in timestamps

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/dwc-for-biologging#18]
@sarahcd it might be an artefact in Excel, but all dates should use `T` to separate date and time in `eventDate` and `measurementDeterminedDate` to be ISO 8601 compliant. So:

```
2014-02-11T21:35:42.000+00:00
```

Rather than:

```
2014-02-11 21:35:42.000+00:00
```

See https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations and http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm:

> T indicates that a time value follows. Any value with a time must begin with T.

**Comment by sarahcd** [comment]
Very glad to have @peterdesmet catching my mistakes :) Will be fixed on the next version I post.
