### ISSUE TITLE
eventTime not following the standard

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#21]
eventTime (https://dwc.tdwg.org/terms/#dwc:eventTime) doesn't look to be following ISO 8601:2004(E)

**Comment by msweetlove** [comment]
I managed to change all event times it to hh:mm:ss in the upcoming version of the data conform ISO 8601. But I think for the timezones required by ISO 8601:2004(E), we need to be pragmatic in the sense that figuring this out based on geographic coordinates for millions of records is computationally unfeasible.

**Comment by pieterprovoost** [comment]
What does `eventTime` currently hold? Is it local time at the release location? Then maybe a conversion to UTC (`HH:MMZ`) is feasible?

**Comment by msweetlove** [comment]
Anton informed me that all times are UTC, so the format is now HH:MM:SSZ (with timezone stamp)
