### ISSUE TITLE
Use of startDayOfYear and endDayOfYear

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#22]
I like the concept of trying to identify the start and end of the track but this is not the correct use of startDayOfYear (https://dwc.tdwg.org/terms/#dwc:startDayOfYear) or endDayOfYear (https://dwc.tdwg.org/terms/#dwc:endDayOfYear). First, is each event a track? Can there be multiple tracks for the same animal? Does the startDayOfYear and endDayOfYear correspond with the footprintWKT such that those three components represent the spatial and temporal aspects of this particular event? If so, I think we might want to use the time time interval option for eventDate (using the ISO 8601:2004(E) recommendations for doing so. So it be something like "2005-10-31/2005-11-9" for eventID: capture:DDU2005_emp_a_f_02.

**Comment by msweetlove** [comment]
We defined each track as an event: starting from the HumanObservation of tagging the animal, followed by a suite of MachineObservations. I don't think there are multiple tracks for one individual, but when certain rare chance events collide (e.g. loosing the tracker, re-capture,...), this possibility cannot be completely excluded. As such, startDayOfYear and endDayOfYear correspond to the footprintWKT of the event, which is aimed to give a first rough estimate of the observation to save query time. Following your proposal, I collapsed the start and endDay columns into the eventDate column. 

(note: although this fix more closely follows the DarwinCore format, I think this makes the resource less straightforward to use, as this complicates querying the dates, while any potential user will need to split the eventDate back into a start and end dates anyway...)

**Comment by albenson-usgs** [comment]
Hmm well we certainly don't want to lose the functionality of the data if we can but we do need to follow the standard as this is not the only dataset being integrated into OBIS (so we must follow the same rules). I wonder if @peterdesmet or @jdpye might have a suggestion on how to keep the start day of the track and end day of the track separate but keeping in line with the standard.

**Comment by peterdesmet** [comment]
As @albenson-usgs mentions, I would definitely not use startDayOfYear and endDayOfYear for this. Note those numbers don’t say anything about the number of days a track is, if that track crosses multiple years.

Using “yyyy-mm-dd/yyyy-mm-dd” in eventDate is the best approach. The occurences will cary a single date anyway.
