### ISSUE TITLE
event file decimalLatitude/decimalLongitude

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#23]
In the event file, what does decimalLatitude and decimalLongitude represent? Is it the midpoint of the track? Something else? It might be good to indicate what it is in georeferenceRemarks (https://dwc.tdwg.org/terms/#dwc:georeferenceRemarks).

**Comment by msweetlove** [comment]
These coordinates are those of the place the animal was physically captured to be able to tag it. This information has now been added to georeferenceRemarks.
