### ISSUE TITLE
location_quality

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#24]
In dynamicProperties there is location_quality. What does this represent? Is it defined somewhere? Would it be better to link to the URI for the definition? Or include a more descriptive version? Is "location_quality: 1" good or bad? As a downstream user, I'm not sure.

**Comment by Antonarctica** [comment]
@albenson-usgs We had a discussion on that in another issue
[https://github.com/tdwg/dwc-for-biologging/issues/19](url)

**Comment by msweetlove** [comment]
This has been resolved using the georeferenceProtocol and georeferenceVerificationStatus terms
