### ISSUE TITLE
U for sex

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#25]
I'm wondering if the use of "U" (which I'm assuming means "unknown" is somehow better than just having NA?

**Comment by msweetlove** [comment]
This was how the sex was noted in the original files I got. I'm also not completely sure if it means unknown. If it does, it still carries more information than NA, as this may implicate the sex could not be determined at first sight (animal was still juvenile?,...). I would propose to leave this as it is.

**Comment by Antonarctica** [comment]
This should be Undetermined which usually means juvenile @jdpye @ianjonsen can you confirm?

**Comment by ianjonsen** [comment]
for RAATD data, these are all vertebrates so sex = NA means that sex was either not recorded or could not be determined. sex = U means that sex could not be determined. The reason why would depend on the species; for some it could mean juvenile, for others it could mean adult sex is too difficult to determine visually.

**Comment by albenson-usgs** [comment]
I feel that it would be better to move "U" to the occurrenceRemarks as U is not a [sex](https://dwc.tdwg.org/terms/#dwc:sex). When we put extraneous information in a term that will not be immediately identifiable to downstream users we are causing confusion. Since U is not a sex we need to be explicit somewhere besides sex that U means sex was undetermined and if it was a juvenile wouldn't it be better to be clearer and use [lifeStage](https://dwc.tdwg.org/terms/#dwc:lifeStage) = juvenile as opposed to having to figure that out from a random letter in sex?

**Comment by Antonarctica** [comment]
I would then just label it as unidentified. sewing the Lifestage won't be possible to do a posteriori for most of these data.

**Comment by peterdesmet** [comment]
Late to the game here. sex = “undetermined” is listed as an acceptable value in http://rs.gbif.org/vocabulary/gbif/sex.xml I have used “unknown” quite often too. Would not use short (and potentially) confusing codes as “U”
