### ISSUE TITLE
type is not used correctly

### ISSUE THREAD

**Issue by albenson-usgs** [tdwg/dwc-for-biologging#27]
type must follow the Dublin Core vocabulary (https://www.dublincore.org/specifications/dublin-core/dcmi-type-vocabulary/2010-10-11/) of which deployment is not one of the options.

**Comment by albenson-usgs** [comment]
Related to issue #9

**Comment by msweetlove** [comment]
removed type from the data, as this information is already shown elsewhere (metadata and basisOfReccord)

**Comment by peterdesmet** [comment]
Generally “Event” is used as type for any observation dataset.
