### ISSUE TITLE
how to create and use footprintWKT

### ISSUE THREAD

**Issue by sarahcd** [tdwg/dwc-for-biologging#4]
Are there any best practices for defining and creating footprintWKT values? The DwC footprintWKT term seems like it has a lot of potential, e.g. to represent the bounds of a track/dataset, home ranges, or possibly to help make tracking datasets discoverable by allowing spatial searches using a footprint rather than millions of observations. Ideally these best practices could address
- how to report footprints for long-distance migrants
- where to describe how a footprint or home range was calculated
- how to address outliers that might or might not have been identified by the owner
- how to address low-accuracy tracking methods

**Comment by peterdesmet** [comment]
For the actual value, you have to close the polygon with the first coordinate again and have them in clockwise order. So:

    POLYGON ((-112.762 43.841, -112.547 43.841, -112.762 43.763, -112.547 43.763))

Should be:

    POLYGON ((-112.762 43.841, -112.547 43.841, -112.547 43.763, -112.762 43.763, -112.762 43.841))

You can test this at https://arthur-e.github.io/Wicket/sandbox-gmaps3.html

**Comment by wardappeltans** [comment]
@peterdesmet @sarahcd see the OBIS manual http://iobis.org/manual/darwincore/#location. If you do not close the footprintWKT you should use LINESTRING.

**Comment by peterdesmet** [comment]
I think `footprintWKT` has potential for a bounding box indeed. Some thoughts:

- I would only populate a footprintWKT for a deployment (which groups many occurrences), not a capture/recovery event (which contains one occurrence)
- I think the footprint should just be for guidance, so I find it less important how it was calculated (i.e. I would calculate it from all min/max coordinates of occurrences except outliers)
- Long distance migrants will have a big bounding box 😄 

Thanks @wardappeltans, good reference. If we want to express a bounding box, we should use POLYGON imo.

**Comment by peggynewman** [comment]
I agree with all of this and have been barking about using footprintWKT to summarise deployment events. I suspect that it would be important to document how the footprint was calculated, especially if we use different home range algorithms to summarise. Alpha hulls might be a useful way of capturing the long ranging migrants.

**Comment by sarahcd** [comment]
I updated the Mahoney use case to close the polygons and list only for deployment events as recommended by @peterdesmet.

**Comment by peterdesmet** [comment]
Thanks @sarahcd, the polygons are still not in clockwise order however. E.g. for `F53:deployment1`:

```
POLYGON ((-112.078   38.510, -111.932 38.510, -112.078 38.230, -111.932 38.230, -112.078 38.510))
```

results in ⏳:

<img width="327" alt="Screenshot 2019-09-13 at 15 33 01" src="https://user-images.githubusercontent.com/600993/64866483-cbac6c00-d63b-11e9-840a-a7d06d399039.png">

Should be:

```
POLYGON ((-112.078 38.510, -111.932 38.510, -111.932 38.230, -112.078 38.230, -112.078 38.510))
```

😄

**Comment by sarahcd** [comment]
Thanks @peterdesmet for catching that, and illustrating why that test site is helpful :) Made the fix.
